version: 0.0
os: linux
files:
  - source: /
    destination: /data
hooks:
  BeforeInstall:
    - location: clearfiles.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: stop.sh
      timeout: 30
      runas: root
